services:
  _defaults:
    autoconfigure: true
    autowire: true
  agentur1601com\logView\EventListener\BackendMenuListener:
    arguments:
      - "@router"
      - "@request_stack"
    tags:
      - { name: kernel.event_listener, event: contao.backend_menu_build, method: onBuild, priority: -255 }
  agentur1601com\logView\Controller\IndexController: ~
