services:
  _defaults:
    autoconfigure: true
    autowire: true
  Agentur1601com\LogView\EventListener\BackendMenuListener:
    tags:
      - { name: kernel.event_listener, event: contao.backend_menu_build, method: onBuild, priority: -255 }
  Agentur1601com\LogView\Controller\IndexController: ~
  Agentur1601com\LogView\Service\Loader\DefaultLoader: ~
  Agentur1601com\LogView\Service\Filter\DefaultFilter: ~
  Agentur1601com\LogView\Service\Parser\SymfonyParser: ~
